/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117810-g1912c86af6-20241117"
#endif /* AVUTIL_FFVERSION_H */
